config/routes.rb
Rails.application.routes.draw do
  resources :exercises
  root "sessions#index"

  #creating a new session, model object(user) has already been created
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #creating a new model opject so we send the route to the users contoller
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  
  resources :workouts
  resources :workout_sessions
  resources :plans
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :workout_sessions
  has_many :workouts, through: :workout_sessions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_workouts, foreign_key: "user_id", class_name: "Workout"
  has_many :plans
  # The :source option specifies the source association name for a has_many :through association, this one specifically is dependent on my Plan Class
  has_many :completed_workouts, through: :plans,  source: :workouts
  #bycrpt gem macro
  has_secure_password

  validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :workout_sessions
  has_many :plans, through: :workout_sessions
  belongs_to :user
  has_many :exercises

  accepts_nested_attributes_for :exercises
end

app/models/workout_session.rb
class WorkoutSession < ApplicationRecord
  belongs_to :plan
  belongs_to :workout
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?


  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new 
    @exercise = Exercise.new 
  end

  def create 
    
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = current_user.plans
  end

  def new
    @plan = Plan.new
  end

  def show
    @plan = Plan.find_by(id: params[:id])
  end

  def create
     # byebug
    # build compared to new adds the newly created plan to the plans collection
    @plan = current_user.plans.build(plan_params)
    
    if @plan.save
      redirect_to plan_path(@plan)
    else
      render :new
    end
  end

  def edit
    @plan = Plan.find_by(id: params[:id])
  end

  def update
    @plan = Plan.find_by(id: params[:id])
    if @plan.update(plan_params)
      redirect_to plan_path(@plan)
    else
      render :edit
    end
  end

  private

# "plan"=>{"title"=>"Test Plan", "description"=>"Awesome Text", "active"=>"1"}
  def plan_params
    params.require(:plan).permit(:title, :description, :active)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    #find user from db
    # name="user[email]"
    @user = User.find_by(email: params[:user][:email])

    #if we find user by email and they have the right password
    if @user && @user.authenticate(params[:user][:password])
      #log the user in, remember user from one page to another
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = "Sorry, please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create 
    # byebug
    @user = User.new(user_params)
    if @user.save
      #user has been saved we now want to remeber the user when they go to the next page
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    # "user"=>{"username"=>"corbintest", "email"=>"corbin@test.com", "password"=>"password"}
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/workout_sessions_controller.rb
class WorkoutSessionsController < ApplicationController
 
  def new 
    @workout_session = WorkoutSession.new
  end
  

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def new
    @workout = Workout.new
    5.times { @workout.exercises.build }
  end

  def index 
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find_by(id: params[:id])
  end

  def create
    # "workout"=>{"title"=>"Workout A", "category"=>"push"}
    @workout = current_user.created_workouts.build(workout_params)
    # byebug
    if @workout.save
      redirect_to workout_path(@workout)
    else
      render :new
    end
  end


  private

  def workout_params
    # "workout"=>{"title"=>"Workout B", "category"=>"pull", "exercises_attributes"=>{"0"=>{"name"=>"Pull Ups", "muscle_group"=>"Back", "equipment"=>"Yourself", "sets"=>"3", "weight"=>"0", "reps"=>"8-12"}
    params.require(:workout).permit(:title, :category, exercises_attributes: [:name, :muscle_group, :equipment, :sets, :weight, :reps])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workout_sessions_helper.rb
module WorkoutSessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_form.html.erb
<%= form_for :exercises do |f| %>
    <div>
    <fieldset>
    <legend>Exercise</legend>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    
    <%= f.label :muscle_group %>
    <%= f.select :muscle_group, options_for_select(%w[abdominals abductors biceps calves chest forearms glutes hamstrings lats lowerback middleback neck quadriceps shoulder traps triceps]), include_blank: true %><br>

    <%= f.label :equipment %>
    <%= f.text_field :equipment %><br>

    <%= f.label :sets %>
    <%= f.number_field :sets, min: 1 %><br>

    <%= f.label :weight %>
    <%= f.number_field :weight, min: 0 %><br>

    <%= f.label :reps %>
    <%= f.text_field :reps %>
    <br><br>

    <%= f.submit "Add Exercise" %>
    </fieldset>
    
    </div>

    

  <% end %>

app/views/exercises/new.html.erb
<h1>Add a new exercise</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiftFit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
      <% if logged_in? %>
      <%= link_to 'Logout', '/logout', method: :delete%>
      <%= link_to 'My Plans', plans_path %>
      <%= link_to 'Create a Plan', new_plan_path %>
      <%= link_to 'Create a Workout', new_workout_path %>
      <%= link_to 'My Workouts', workouts_path %>
      <% end %>
      
  
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_for @plan do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br></br>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br></br>

  <%= f.label :active %>
  <%= f.check_box :active %>

    <br></br>

  <%= f.submit%>

<% end %>

app/views/plans/edit.html.erb
<h1>Edit <%= @plan.title %></h1>

<%= render "form" %>

app/views/plans/index.html.erb
  
<h1>Your Plans</h1>

<% @plans.each do |plan|%>
  <div>
    <h3><%= link_to plan.title, plan_path(plan) %> </h3>
    <p>About: <%= plan.description %> </p>
  </div><br>
<% end %>

app/views/plans/new.html.erb
<h1>Create a new plan</h1>

<%= render 'form' %>

app/views/plans/show.html.erb
<h1> <%= @plan.title %> </h1>

<p> <%= @plan.description %> </p>


<%= link_to "Edit Plan", edit_plan_path(@plan) %>

app/views/users/new.html.erb
<h2>Sign up here</h2>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%# required:true does not protect on the backend %>
  <%= f.text_field :username   %>
  
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

    <%=f.label :password_confirmation %>
    <%=f.password_field :password_confirmation%>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %> </h1>

app/views/workout_sessions/new.html.erb
<h1>Track a Workout</h1>

<%= form_for @workout_session do |f| %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :feeling %>
  <%= f.text_field :feeling %>

  <br><br>

  <%= f.label :plan_id %>
  <%#  collection_select(method, collection, value_method, text_method) %>
  <%= f.collection_select :plan_id, Plan.all, :id, :title %>

  <br><br>

  <%= f.label :workout_id %>
  <%= f.collection_select :workout_id, Workout.all, :id, :title %>

  <%= f.fields_for :workout do |workout| %>
    

  <% end %>

  <%= f.submit %>  
<% end %>
  

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
    <br></br>

  <%= f.label :category %>
  <%= f.select :category,options_for_select(%w[weights cardio HIIT strength bodybuilding endurance aerobic plyometrics cross-training interval resistance]), include_blank: true  %>
    <br></br>

  <%= f.fields_for :exercises do |exercise_attributes| %>
    <div>
    <fieldset>
    <legend>Exercise</legend>
    <%= exercise_attributes.label :name %>
    <%= exercise_attributes.text_field :name %><br>
    
    <%= exercise_attributes.label :muscle_group %>
    <%= exercise_attributes.select :muscle_group, options_for_select(%w[abdominals abductors biceps calves chest forearms glutes hamstrings lats lowerback middleback neck quadriceps shoulder traps triceps]), include_blank: true %><br>

    <%= exercise_attributes.label :equipment %>
    <%= exercise_attributes.text_field :equipment %><br>

    <%= exercise_attributes.label :sets %>
    <%= exercise_attributes.number_field :sets, min: 1 %><br>

    <%= exercise_attributes.label :weight %>
    <%= exercise_attributes.number_field :weight, min: 0 %><br>

    <%= exercise_attributes.label :reps %>
    <%= exercise_attributes.text_field :reps %>
    </fieldset>
    <br><br>
    </div>

  <% end %>
  <%= f.submit%>

<% end %>

app/views/workouts/index.html.erb
<% @workouts.each do |e| %>
  <h1><%= link_to e.title, workout_path(e) %></h1>
  <p><%= e.description %></p>
    
 <% end %>

app/views/workouts/new.html.erb
<h1>Add a New Workout</h1>

<%= render 'form' %>

app/views/workouts/show.html.erb
<h1> <%= @workout.title %> </h1>

<ul>
<% @workout.exercises.each do |e| %>
  <fieldset>
    <legend><strong><%= e.name %></strong></legend>
    <p>Sets: <%= e.sets %></p
    <p>Reps: <%= e.reps %></p>
    <p>Weight: <%= e.weight %> lbs</p>
  </fieldset>
  <br>
  <% end %>
  </ul>